package EmbuscadoCoffee;

import javax.swing.JOptionPane;

import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import java.awt.Font;
import java.awt.EventQueue;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.SwingConstants;
import java.awt.Dialog.ModalExclusionType;
import java.awt.Dimension;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.border.LineBorder;
import javax.swing.border.BevelBorder;
import javax.swing.border.MatteBorder;
import javax.swing.border.SoftBevelBorder;
import javax.swing.ScrollPaneConstants;

/**
 * Programmer: Embuscado, Geoffrey C.
 * Professor: Professor Ellane Cervantes
 * Subject code: ITC12
 * Project name: Case Study 2: Coffee Shop
 * JAVA IDE: NetBeans IDE 7.1
 * 
 */
public class CoffeeLeCaprio extends javax.swing.JFrame {

    /**
     * Creates new form CoffeeLeCaprio
     */
    public CoffeeLeCaprio() {
    	setResizable(false);
    	getContentPane().setBackground(new Color(255, 255, 255));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(0, 1, 452, 79);
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel1.setVerticalAlignment(SwingConstants.TOP);
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBounds(10, 86, 442, 26);
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton1.setVerticalAlignment(SwingConstants.TOP);
        jButton1.setBackground(new Color(240, 230, 140));
        jButton1.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton1.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton1.setBounds(10, 116, 223, 32);
        jButton3 = new javax.swing.JButton();
        jButton3.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton3.setBackground(new Color(240, 230, 140));
        jButton3.setVerticalAlignment(SwingConstants.TOP);
        jButton3.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton3.setBounds(229, 261, 223, 32);
        jButton4 = new javax.swing.JButton();
        jButton4.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton4.setBackground(new Color(240, 230, 140));
        jButton4.setVerticalAlignment(SwingConstants.TOP);
        jButton4.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton4.setBounds(10, 147, 223, 32);
        jButton5 = new javax.swing.JButton();
        jButton5.setBackground(new Color(240, 230, 140));
        jButton5.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton5.setVerticalAlignment(SwingConstants.TOP);
        jButton5.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton5.setBounds(10, 176, 223, 32);
        jButton6 = new javax.swing.JButton();
        jButton6.setBackground(new Color(240, 230, 140));
        jButton6.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton6.setVerticalAlignment(SwingConstants.TOP);
        jButton6.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton6.setBounds(10, 205, 223, 32);
        jButton7 = new javax.swing.JButton();
        jButton7.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton7.setBackground(new Color(240, 230, 140));
        jButton7.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton7.setVerticalAlignment(SwingConstants.TOP);
        jButton7.setBounds(10, 232, 223, 32);
        jButton8 = new javax.swing.JButton();
        jButton8.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton8.setBackground(new Color(240, 230, 140));
        jButton8.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton8.setVerticalAlignment(SwingConstants.TOP);
        jButton8.setBounds(10, 261, 223, 32);
        jButton9 = new javax.swing.JButton();
        jButton9.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton9.setBackground(new Color(240, 230, 140));
        jButton9.setVerticalAlignment(SwingConstants.TOP);
        jButton9.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton9.setBounds(229, 116, 223, 39);
        jButton10 = new javax.swing.JButton();
        jButton10.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton10.setBackground(new Color(240, 230, 140));
        jButton10.setVerticalAlignment(SwingConstants.TOP);
        jButton10.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton10.setBounds(229, 150, 223, 32);
        jButton11 = new javax.swing.JButton();
        jButton11.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton11.setBackground(new Color(240, 230, 140));
        jButton11.setVerticalAlignment(SwingConstants.TOP);
        jButton11.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton11.setBounds(229, 179, 223, 32);
        jButton12 = new javax.swing.JButton();
        jButton12.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton12.setBackground(new Color(240, 230, 140));
        jButton12.setVerticalAlignment(SwingConstants.TOP);
        jButton12.setFont(new Font("Gabriola", Font.BOLD, 24));
        jButton12.setBounds(229, 208, 223, 32);
        jButton13 = new javax.swing.JButton();
        jButton13.setBackground(new Color(240, 230, 140));
        jButton13.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton13.setVerticalAlignment(SwingConstants.TOP);
        jButton13.setFont(new Font("Gabriola", Font.BOLD, 23));
        jButton13.setBounds(229, 235, 223, 32);
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setBounds(10, 301, 119, 43);
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane2.setBorder(new LineBorder(new Color(0, 0, 0)));
        jScrollPane2.setBackground(new Color(238, 232, 170));
        jScrollPane2.setBounds(135, 301, 317, 43);
        jTextArea1 = new javax.swing.JTextArea();
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setBorder(null);
        jTextArea1.setBackground(new Color(238, 232, 170));
        jTextArea1.setForeground(new Color(0, 0, 0));
        jTextArea1.setFont(new Font("Tahoma", Font.PLAIN, 15));
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setBounds(458, 1, 423, 335);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(887, 1, 113, 524);
        jLabel8 = new javax.swing.JLabel();
        jLabel8.setBounds(573, 342, 308, 185);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel3.setVerticalAlignment(SwingConstants.TOP);
        jLabel3.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel3.setBounds(278, 357, 49, 22);
        jTextField1 = new javax.swing.JTextField();
        jTextField1.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField1.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField1.setBackground(new Color(238, 232, 170));
        jTextField1.setBounds(337, 355, 66, 24);
        jLabel9 = new javax.swing.JLabel();
        jLabel9.setVerticalAlignment(SwingConstants.TOP);
        jLabel9.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel9.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel9.setBounds(278, 384, 72, 22);
        jTextField2 = new javax.swing.JTextField();
        jTextField2.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField2.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField2.setBackground(new Color(238, 232, 170));
        jTextField2.setBounds(360, 385, 43, 23);
        jLabel10 = new javax.swing.JLabel();
        jLabel10.setVerticalAlignment(SwingConstants.TOP);
        jLabel10.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel10.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel10.setBounds(278, 410, 51, 26);
        jTextField3 = new javax.swing.JTextField();
        jTextField3.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField3.setBackground(new Color(238, 232, 170));
        jTextField3.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField3.setBounds(339, 414, 64, 22);
        jButton14 = new javax.swing.JButton();
        jButton14.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton14.setBackground(new Color(240, 230, 140));
        jButton14.setVerticalAlignment(SwingConstants.TOP);
        jButton14.setFont(new Font("Gabriola", Font.BOLD, 18));
        jButton14.setBounds(413, 356, 152, 22);
        jButton15 = new javax.swing.JButton();
        jButton15.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton15.setBackground(new Color(240, 230, 140));
        jButton15.setVerticalAlignment(SwingConstants.TOP);
        jButton15.setFont(new Font("Gabriola", Font.BOLD, 18));
        jButton15.setBounds(413, 385, 152, 22);
        jButton16 = new javax.swing.JButton();
        jButton16.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton16.setBackground(new Color(240, 230, 140));
        jButton16.setFont(new Font("Gabriola", Font.BOLD, 18));
        jButton16.setVerticalAlignment(SwingConstants.TOP);
        jButton16.setBounds(413, 413, 152, 23);
        jLabel11 = new javax.swing.JLabel();
        jLabel11.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel11.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel11.setVerticalAlignment(SwingConstants.TOP);
        jLabel11.setBounds(204, 469, 111, 22);
        jTextField4 = new javax.swing.JTextField();
        jTextField4.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField4.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField4.setBackground(new Color(238, 232, 170));
        jTextField4.setBounds(314, 466, 138, 23);
        jLabel12 = new javax.swing.JLabel();
        jLabel12.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel12.setVerticalAlignment(SwingConstants.TOP);
        jLabel12.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel12.setBounds(20, 357, 138, 22);
        jTextField6 = new javax.swing.JTextField();
        jTextField6.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField6.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField6.setBackground(new Color(238, 232, 170));
        jTextField6.setBounds(171, 361, 97, 20);
        jLabel13 = new javax.swing.JLabel();
        jLabel13.setVerticalAlignment(SwingConstants.TOP);
        jLabel13.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel13.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel13.setBounds(8, 386, 150, 22);
        jTextField5 = new javax.swing.JTextField();
        jTextField5.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField5.setBackground(new Color(238, 232, 170));
        jTextField5.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField5.setBounds(171, 388, 97, 20);
        jLabel15 = new javax.swing.JLabel();
        jLabel15.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel15.setVerticalAlignment(SwingConstants.TOP);
        jLabel15.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel15.setBounds(214, 496, 90, 22);
        jTextField7 = new javax.swing.JTextField();
        jTextField7.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField7.setBackground(new Color(238, 232, 170));
        jTextField7.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField7.setBounds(312, 500, 140, 20);
        jLabel16 = new javax.swing.JLabel();
        jLabel16.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel16.setVerticalAlignment(SwingConstants.TOP);
        jLabel16.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel16.setBounds(482, 469, 69, 32);
        jTextField8 = new javax.swing.JTextField();
        jTextField8.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField8.setBackground(new Color(238, 232, 170));
        jTextField8.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField8.setBounds(458, 500, 107, 20);
        jButton18 = new javax.swing.JButton();
        jButton18.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton18.setBackground(new Color(240, 230, 140));
        jButton18.setFont(new Font("Gabriola", Font.BOLD, 18));
        jButton18.setVerticalAlignment(SwingConstants.TOP);
        jButton18.setBounds(454, 444, 111, 25);
        jButton17 = new javax.swing.JButton();
        jButton17.setBorder(new LineBorder(new Color(160, 82, 45), 2, true));
        jButton17.setBackground(new Color(240, 230, 140));
        jButton17.setVerticalAlignment(SwingConstants.TOP);
        jButton17.setFont(new Font("Gabriola", Font.BOLD, 18));
        jButton17.setBounds(33, 430, 138, 23);
        jLabel17 = new javax.swing.JLabel();
        jLabel17.setVerticalAlignment(SwingConstants.TOP);
        jLabel17.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel17.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel17.setBounds(0, 469, 129, 22);
        jLabel18 = new javax.swing.JLabel();
        jLabel18.setVerticalAlignment(SwingConstants.TOP);
        jLabel18.setHorizontalAlignment(SwingConstants.CENTER);
        jLabel18.setForeground(UIManager.getColor("inactiveCaptionText"));
        jLabel18.setBounds(10, 496, 62, 22);
        jTextField9 = new javax.swing.JTextField();
        jTextField9.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField9.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField9.setBackground(new Color(238, 232, 170));
        jTextField9.setBounds(125, 469, 79, 20);
        jTextField10 = new javax.swing.JTextField();
        jTextField10.setBorder(new LineBorder(new Color(0, 0, 0)));
        jTextField10.setBackground(new Color(238, 232, 170));
        jTextField10.setFont(new Font("Tahoma", Font.BOLD, 15));
        jTextField10.setBounds(76, 500, 128, 20);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Caffeine Coffee Shop System");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("CoffeeEmbuscadoFrame");
        setPreferredSize(new Dimension(1020, 575));

        jPanel1.setBackground(new Color(160, 82, 45));

        jLabel2.setFont(new java.awt.Font("Segoe Print", 1, 14)); // NOI18N
        jLabel2.setForeground(new Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Spread the love from its sweetness and aroma");

        jLabel1.setFont(new Font("Gabriola", Font.BOLD, 28)); // NOI18N
        jLabel1.setForeground(new Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("The Caffeine Coffee Shop");
        
        JPanel panel = new JPanel();
        panel.setBackground(new Color(160, 82, 45));
    
    
        

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(panel, GroupLayout.PREFERRED_SIZE, 88, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addPreferredGap(ComponentPlacement.UNRELATED)
        					.addComponent(jLabel2, GroupLayout.DEFAULT_SIZE, 334, Short.MAX_VALUE))
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addGap(44)
        					.addComponent(jLabel1)))
        			.addGap(452))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addContainerGap()
        			.addGroup(jPanel1Layout.createParallelGroup(Alignment.TRAILING)
        				.addComponent(panel, Alignment.LEADING, GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
        				.addGroup(jPanel1Layout.createSequentialGroup()
        					.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
        					.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        					.addComponent(jLabel2)))
        			.addGap(86))
        );
        panel.setLayout(null);
        
        display_image = new JLabel("");
        display_image.setBackground(new Color(160, 82, 45));
        display_image.setVerticalAlignment(SwingConstants.TOP);
        display_image.setHorizontalAlignment(SwingConstants.CENTER);
        display_image.setIcon(new ImageIcon(CoffeeLeCaprio.class.getResource("/EmbuscadoCoffee/logo-icon.png")));
        display_image.setBounds(0, 0, 89, 64);
        panel.add(display_image);
        jPanel1.setLayout(jPanel1Layout);

        jPanel2.setBackground(new Color(160, 82, 45));

        jLabel14.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Cold Coffee");
        
        lblNewLabel = new JLabel("Hot Coffe");
        lblNewLabel.setFont(new Font("Gabriola", Font.BOLD, 24));
        lblNewLabel.setHorizontalAlignment(SwingConstants.CENTER);
        lblNewLabel.setForeground(new Color(255, 255, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(62)
        			.addComponent(lblNewLabel)
        			.addPreferredGap(ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
        			.addComponent(jLabel14)
        			.addGap(60))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        			.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(lblNewLabel)
        				.addComponent(jLabel14))
        			.addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2.setLayout(jPanel2Layout);

        jButton1.setText("Coffee Americano");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton3.setText("Coffee Milk");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Cafe Mocha");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Espresso Romano");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Cappuccino");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Cafe Zorro");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Guillermo");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("Greek Frapped");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("Green Eye");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setText("Raspberry Mocha");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setText("Red Tie");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setText("YuanYang");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new Color(160, 82, 45));

        jLabel7.setFont(new java.awt.Font("Gabriola", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Description");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4Layout.setHorizontalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel7)
        			.addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
        	jPanel4Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(Alignment.LEADING, jPanel4Layout.createSequentialGroup()
        			.addContainerGap()
        			.addComponent(jLabel7, GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        			.addContainerGap())
        );
        jPanel4.setLayout(jPanel4Layout);

        jTextArea1.setColumns(20);
        jTextArea1.setEditable(false);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmbuscadoCoffee/menus.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmbuscadoCoffee/menuscold12.jpg"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/EmbuscadoCoffee/MenusCold11.jpg"))); // NOI18N

        jLabel3.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel3.setText("Small");

        jLabel9.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel9.setText("Medium");

        jLabel10.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel10.setText("Large");

        jButton14.setText("SELECT SMALL");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("SELECT MEDIUM");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setText("SELECT LARGE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel11.setText("Your Order");

        jLabel12.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel12.setText("Enter Quantity");

        jLabel13.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel13.setText("Enter Input Val.");

        jLabel15.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel15.setText("Total Val.");

        jLabel16.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel16.setText("Change");

        jButton18.setText("Senior Citizen");
        jButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton18ActionPerformed(evt);
            }
        });

        jButton17.setText("Get Gross & VAT");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        jLabel17.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel17.setText("VAT Amount");

        jLabel18.setFont(new Font("Gabriola", Font.BOLD, 25)); // NOI18N
        jLabel18.setText("GROSS");
        getContentPane().setLayout(null);
        getContentPane().add(jPanel1);
        getContentPane().add(jPanel4);
        getContentPane().add(jScrollPane2);
        getContentPane().add(jPanel2);
        getContentPane().add(jButton1);
        getContentPane().add(jButton8);
        getContentPane().add(jButton6);
        getContentPane().add(jButton4);
        getContentPane().add(jButton5);
        getContentPane().add(jButton7);
        getContentPane().add(jButton3);
        getContentPane().add(jLabel3);
        getContentPane().add(jTextField1);
        getContentPane().add(jLabel9);
        getContentPane().add(jTextField2);
        getContentPane().add(jLabel10);
        getContentPane().add(jTextField3);
        getContentPane().add(jButton15);
        getContentPane().add(jButton14);
        getContentPane().add(jButton16);
        getContentPane().add(jLabel17);
        getContentPane().add(jTextField9);
        getContentPane().add(jLabel18);
        getContentPane().add(jTextField10);
        getContentPane().add(jButton10);
        getContentPane().add(jButton11);
        getContentPane().add(jButton12);
        getContentPane().add(jButton13);
        getContentPane().add(jButton9);
        getContentPane().add(jTextField4);
        getContentPane().add(jLabel12);
        getContentPane().add(jTextField6);
        getContentPane().add(jLabel11);
        getContentPane().add(jLabel13);
        getContentPane().add(jLabel15);
        getContentPane().add(jTextField7);
        getContentPane().add(jTextField5);
        getContentPane().add(jLabel6);
        getContentPane().add(jTextField8);
        getContentPane().add(jButton18);
        getContentPane().add(jLabel16);
        getContentPane().add(jButton17);
        getContentPane().add(jLabel8);
        getContentPane().add(jLabel4);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Greek Frapped");
        jTextField1.setText("65");
        jTextField2.setText("75");
        jTextField3.setText("90");
        jTextArea1.setText("Foam-covered iced coffee\ndrink made from spray-dried\ninstant coffee.");
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here
        this.jTextField4.setText("Coffee America");
        this.jTextField1.setText("120");
        this.jTextField2.setText("145");
        this.jTextField3.setText("178");
        this.jTextArea1.setText("Style of coffee prepared by \nadding hot waterto espresso,\ngiving a similar strength to but\ndifferent flavor from regular drip\ncoffee.");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Coffee Milk");
        this.jTextField1.setText("90");
        this.jTextField2.setText("100");
        this.jTextField3.setText("120");
        this.jTextArea1.setText("Drink similar to chocolate milk;\nhowever, instead of chocolate\nsyrup, coffee syrup is used.");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Coffee Mocha");
        this.jTextField1.setText("135");
        this.jTextField2.setText("145");
        this.jTextField3.setText("165");
        this.jTextArea1.setText("It is typically one third espresso\nand two thirds steamed milk,\nbut a portion of chocolate is\nadded, typically in the form\nof a chocolate syrup, although\nother vending systems use\ninstant chocolate powder");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Espresso Romano");
        this.jTextField1.setText("188");
        this.jTextField2.setText("224");
        this.jTextField3.setText("244");
        this.jTextArea1.setText("a shot of espresso with a small\nring of lemon and sugar added");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        this.jTextField1.setText("N/A");
        this.jTextField2.setText("122");
        this.jTextField3.setText("144");
        this.jTextField4.setText("Cappuccino");
        this.jTextArea1.setText("Coffee-based drink prepared\nwith espresso, hot milk, and steamed\nmilk foam.");
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        this.jTextField1.setText("N/A");
        this.jTextField2.setText("179");
        this.jTextField3.setText("196");
        this.jTextField4.setText("Guillermo");
        this.jTextArea1.setText("One or two shots of hot\nespresso, poured over slices of\nlime it can also be served\non ice, sometimes with a touch of milk.");
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.jTextField1.setText("N/A");
        this.jTextField2.setText("190");
        this.jTextField3.setText("220");
        this.jTextField4.setText("Cafe Zorro");
        this.jTextArea1.setText("Double espresso added to\nhot water. ratio 1:1");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Green Eye");
        this.jTextField1.setText("123");
        this.jTextField2.setText("135");
        this.jTextField3.setText("142");
        this.jTextArea1.setText("Dripped coffee with a\ntriple shot of espresso.");
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("Raspberry Mocha");
        this.jTextField1.setText("126");
        this.jTextField2.setText("145");
        this.jTextField3.setText("N/A");
        this.jTextArea1.setText("A regular mocha with\nraspberry flavoring.");
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
        //154,166,179
        this.jTextField4.setText("Red Tie");
        this.jTextField1.setText("154");
        this.jTextField2.setText("166");
        this.jTextField3.setText("179");
        this.jTextArea1.setText("A traditional\nThai Iced Tea,\nwhich is a spicy and sweet");
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        this.jTextField4.setText("YuanYang");
        this.jTextField1.setText("97");
        this.jTextField2.setText("127");
        this.jTextField3.setText("143");
        this.jTextArea1.setText("Made of a mixture of\ncoffee and Hong Kong-style\nmilk tea.");
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        int smallC,totalEmbuscado,Change,inputVal,Quant;
        try{
            smallC=Integer.parseInt(this.jTextField1.getText());
        }
        catch(Exception Embuscdo){
            JOptionPane.showMessageDialog(this,"Price is not ATTENDING","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        inputVal=Integer.parseInt(this.jTextField5.getText());
        Quant=Integer.parseInt(this.jTextField6.getText());
        totalEmbuscado=smallC*Quant;
        Change=inputVal-totalEmbuscado;
        String Tot1=String.valueOf(totalEmbuscado);
        String Cha1=String.valueOf(Change);
        this.jTextField7.setText(Tot1);
        this.jTextField8.setText(Cha1);
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton18ActionPerformed
        double intputVal3,startingTotalEmbuscado,startingChangeEmbuscado,SeniorsTotal,SeniorsChange;
        startingTotalEmbuscado=Integer.parseInt(this.jTextField7.getText());
        startingChangeEmbuscado=Integer.parseInt(this.jTextField8.getText());
        intputVal3=Integer.parseInt(this.jTextField5.getText());
        SeniorsChange=intputVal3*.12;
        SeniorsTotal=intputVal3*.88;
        String OlderFo=String.valueOf(SeniorsChange);
        String OlderTo=String.valueOf(SeniorsTotal);
        this.jTextField7.setText(OlderTo);
        this.jTextField8.setText(OlderFo);
    }//GEN-LAST:event_jButton18ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int medC,totalEmbuscado2,Change2,inputVal2,Quant2;
        try{
            medC=Integer.parseInt(this.jTextField2.getText());
        }
        catch(Exception Embuscdo2){
            JOptionPane.showMessageDialog(this,"Price is not ATTENDING","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        inputVal2=Integer.parseInt(this.jTextField5.getText());
        Quant2=Integer.parseInt(this.jTextField6.getText());
        totalEmbuscado2=medC*Quant2;
        Change2=inputVal2-totalEmbuscado2;
        String Tot1=String.valueOf(totalEmbuscado2);
        String Cha1=String.valueOf(Change2);
        this.jTextField7.setText(Tot1);
        this.jTextField8.setText(Cha1);
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        int larC,totalEmbuscado3,Change3,inputVal3,Quant3;
        try{
            larC=Integer.parseInt(this.jTextField3.getText());
        }
        catch(Exception Embuscdo3){
            JOptionPane.showMessageDialog(this,"Price is not ATTENDING","ERROR",JOptionPane.ERROR_MESSAGE);
            return;
        }
        inputVal3=Integer.parseInt(this.jTextField5.getText());
        Quant3=Integer.parseInt(this.jTextField6.getText());
        totalEmbuscado3=larC*Quant3;
        Change3=inputVal3-totalEmbuscado3;
        String Tot4=String.valueOf(totalEmbuscado3);
        String Cha4=String.valueOf(Change3);
        this.jTextField7.setText(Tot4);
        this.jTextField8.setText(Cha4);
    }//GEN-LAST:event_jButton16ActionPerformed

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton17ActionPerformed
        // TODO add your handling code here:
        double TotMA,Gross,VAT;
        TotMA=Double.parseDouble(this.jTextField7.getText());
        VAT=TotMA*.12;
        Gross=VAT+TotMA;
        double VATZ=Math.round(VAT);
        double GROZZ=Math.round(Gross);
        String VATs=String.valueOf(VATZ);
        String GROSS=String.valueOf(GROZZ);
        this.jTextField9.setText(VATs);
        this.jTextField10.setText(GROSS);
        
    }//GEN-LAST:event_jButton17ActionPerformed

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private JLabel display_image;
    private JLabel lblNewLabel;
}